---
title: "Project-IE6200-Sec2-Group10"
output: pdf_document
---

```{r}
# Importing libraries
library(tidyverse)
library(lubridate)
library(reshape2)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(corrplot)
library(fitdistrplus)
library(mapproj)
```

```{r}
hb16_df <- data.frame(read.csv("h1b16.csv", header = TRUE, sep = ,))
hb17_df <- data.frame(read.csv("h1b17.csv", header = TRUE, sep = ,))
hb18_df <- data.frame(read.csv("h1b18.csv", header = TRUE, sep = ,))

# Data Science Vector
data_science_jobs <- c("DATA SCIENTIST", "BUSINESS ANALYST", "DATA ANALYST", "DATA ENGINEER")

data_science_df <- hb16_df %>% filter(JOB_TITLE %in% data_science_jobs)

data_science_fulltime <- data_science_df %>% 
  filter(FULL_TIME_POSITION == "Y")

data_science_parttime <- data_science_df %>% 
  filter(FULL_TIME_POSITION == "N")

# Full Time Data Science
mean(data_science_fulltime$PREVAILING_WAGE)
median(data_science_fulltime$PREVAILING_WAGE)
range(data_science_fulltime$PREVAILING_WAGE)
quantile(data_science_fulltime$PREVAILING_WAGE)
var(data_science_fulltime$PREVAILING_WAGE)
sd(data_science_fulltime$PREVAILING_WAGE)

# Compare differnet datasets, use coefficient of variation
coefficient_of_variation_fulltime = (sd(data_science_fulltime$PREVAILING_WAGE) / mean(data_science_fulltime$PREVAILING_WAGE)) * 100 
coefficient_of_variation_fulltime

# Part Time Data Science
mean(data_science_parttime$PREVAILING_WAGE)
median(data_science_parttime$PREVAILING_WAGE)
range(data_science_parttime$PREVAILING_WAGE)
quantile(data_science_parttime$PREVAILING_WAGE)
var(data_science_parttime$PREVAILING_WAGE)
sd(data_science_parttime$PREVAILING_WAGE)

# Compare differnet datasets, use coefficient of variation
coefficient_of_variation_parttime = (sd(data_science_parttime$PREVAILING_WAGE) / mean(data_science_parttime$PREVAILING_WAGE)) * 100
coefficient_of_variation_parttime
```
## Histogram

```{r}
applications_11_16 <- data_science_df %>% 
  group_by(YEAR) %>% 
  summarise(noOfApplications = n())
```

```{r}
applications_17 <- hb17_df %>% 
  filter(JOB_TITLE %in% data_science_jobs) %>% 
  summarise(noOfApplications = n()) %>% 
  mutate(
    `YEAR` = 2017,
    )

applications_18 <- hb18_df %>% 
  filter(JOB_TITLE %in% data_science_jobs) %>% 
  summarise(noOfApplications = n()) %>% 
  mutate(
    `YEAR` = 2018,
    )
  
application_11_17 <- rbind(applications_11_16,applications_17)

applications_datascience <- rbind(application_11_17,applications_18)

applications_datascience%>%
  ggplot(mapping=aes(x= as.character(YEAR), y= noOfApplications)) +
  geom_bar(stat="identity", fill="steelblue") +
  ggtitle("No of applications per year for Data Science jobs") +
  labs(y="Count of Applications", x = "Year") +
  theme_minimal()

```
## Top 10 Companies that provide Data Science Jobs

```{r}
companies_ds_df <- data_science_df %>% 
  group_by(EMPLOYER_NAME) %>% 
  summarise(total = n()) %>% 
  arrange(desc(total))

companies_ds_df <- companies_ds_df[1:10,]

companies_ds_df%>%
  ggplot(mapping=aes(x= total, y=EMPLOYER_NAME)) +
  geom_bar(stat="identity", fill="steelblue") +
  ggtitle("Companies that provide the most H1B for Data Science jobs") +
  labs(y="Companies", x = "Total") +
  theme_minimal()
```
## Top 10 Companies 2011 - 2016

```{r}
companies_df <- hb16_df %>% 
  group_by(EMPLOYER_NAME) %>% 
  summarise(total = n()) %>% 
  arrange(desc(total))

companies_df <- companies_df[1:10,]

companies_df%>%
  ggplot(mapping=aes(x= as.integer(total), y=EMPLOYER_NAME)) +
  geom_bar(stat="identity", fill="steelblue") +
  ggtitle("Companies that provide the most H1B") +
  labs(y="Companies", x = "Total") +
  theme_minimal()

```

```{r}
accepted_rejected_df <- hb16_df %>% 
  group_by(CASE_STATUS) %>% 
  summarise(total = n()) %>% 
  drop_na()

# TODO:  Could be a better pie chart
labels <- c("CERTIFIED", "CERTIFIED-WITHDRAWN", "DENIED", "INVALIDATED", "IN REVIEW", "REJECTED", "WITHDRAWN")
myPalette <- brewer.pal(5, "Set2") 
pie(accepted_rejected_df$total, labels, border="white", col=myPalette)

# Basic piechart
ggplot(accepted_rejected_df, aes(x="", y=total, fill=CASE_STATUS)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() +
  ggtitle("Status of applications")

```
```{r}

wage_df <- data_science_df %>% 
  group_by(PREVAILING_WAGE) %>% 
  summarise(total = n()) %>% 
  drop_na() %>% 
  arrange(desc(PREVAILING_WAGE = FALSE))

nrow(wage_df)

ggplot(data_science_df, aes(x = PREVAILING_WAGE)) +
  geom_histogram(bins = 30, color = 'Black', fill = 'steelblue')

certified_h1b <- hb16_df %>% 
  filter(CASE_STATUS == "CERTIFIED")

ggplot(hb17_df, aes(x = as.Date(EMPLOYMENT_START_DATE))) +
  geom_histogram(bins = 70, color = 'Black', fill = 'steelblue')


```


```{r}

h1b <- data.frame(lapply(hb16_df, function(v) {
  if (is.factor(v)) return(toupper(v))
  else return(v)
}))

h1b <- tbl_df(h1b)
glimpse(h1b)

# ------------------------------------------------------------------------------------------------------------------------------

# Split WORKSITE column into two columns: city and state
h1b <- h1b %>%
    separate(WORKSITE, c("CITY", "STATE"), ", ")

# Change variables 'STATE' and 'YEAR' to ordered factors
h1b$STATE <- factor(h1b$STATE, ordered = TRUE)
h1b$YEAR <- factor(h1b$YEAR, ordered = TRUE)

# ------------------------------------------------------------------------------------------------------------------------------
# Keep only "CERTIFIED" H1B cases
certified_h1b <- h1b %>%
    filter(CASE_STATUS == "CERTIFIED")

# Generate a sample of wages and filter out NA values
set.seed(123)
wage_sample <- subset(certified_h1b[sample(1:nrow(certified_h1b), 300000), 7], 
                      !is.na(PREVAILING_WAGE))

# Histogram of sampled wages
ggplot(subset(wage_sample, 
              PREVAILING_WAGE >= quantile(PREVAILING_WAGE, 0.1) & 
                  PREVAILING_WAGE <= quantile(PREVAILING_WAGE, 0.95)), 
              aes(x = PREVAILING_WAGE)) + 
    geom_histogram(binwidth = 1000,
                   col = "red", 
                   fill = "blue", 
                   alpha = .2) +
    scale_x_continuous(breaks = seq(min(wage_sample$PREVAILING_WAGE), 
                                    max(wage_sample$PREVAILING_WAGE),
                                    5000)) +
    labs(title = "Histogram of Prevailing Wage)", 
         x = "prevailing wage")

```
```{r}

descdist(wage_sample$PREVAILING_WAGE)
```
```{r}
# Import state data containing state abbreviations and locations
data(state)
states <- data.frame(state.abb, state.name, state.area, state.center,
                     state.division, state.region, state.x77)

row.names(states) <- NULL
states <- states %>%
    select(state.abb, state.name, x, y, Population, Income, Illiteracy)
states <- subset(states, ! state.abb %in% c("HI", "AK"))


# Count H1B petitions filed by each state
petition_by_state <- certified_h1b %>%
    filter(STATE != "NA") %>%
    group_by(region = tolower(STATE)) %>%
    summarise(no_petitions = n()) %>%
    arrange(desc(no_petitions))


# Draw the map
us_states <- map_data("state")

petition_by_state <- inner_join(petition_by_state, us_states, by = "region")

plot_petition_by_state <- ggplot(petition_by_state, aes(x = long, y = lat, group = group)) +
    geom_polygon(aes(fill = cut_number(no_petitions, 7, dig.lab=6))) +
    geom_path(color = "gray", linestyle = 2) +
    coord_map() +
    geom_text(data = states, aes(x = x, y = y, label = state.abb, group = NULL),
              size = 4, color = "white") +
    scale_fill_brewer('Number of petitions', palette  = 'PuRd', label = scales::comma) +
    ggtitle("H1B petitions by state") +
    theme_bw()
    
plot_petition_by_state
```

